flag=-Xlint:unchecked
# test
test:
	javac Test.java #$(flag)
	java Test

# practica 1
1c:
	javac practica1/CircularQ/TestCQ_ite.java
	java practica1.CircularQ.TestCQ_ite
1l:
	javac practica1/LinkedQ/TestLQ_ite.java
	java practica1.LinkedQ.TestLQ_ite
1p:
	javac practica1/Protocol/Test.java
	java practica1.Protocol.Test

# practica 2
2cz:
	javac practica2/P0CZ/TestSum.java
	java practica2.P0CZ.TestSum
2czm:
	javac practica2/P0CZ/Monitor/TestSumCZ.java
	java practica2.P0CZ.Monitor.TestSumCZ
2s:
	javac practica2/P1Sync/TestID.java
	java practica2.P1Sync.TestID
2sm:
	javac practica2/P1Sync/Monitor/TestIDSync.java
	java practica2.P1Sync.Monitor.TestIDSync
2p:
	javac practica2/Protocol/Test.java
	java practica2.Protocol.Test

# practica 3
3:
	javac practica3/Test.java
	java practica3.Test
